# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1bced32c2c705e3b2d4ca2f5bf3369635ba6592eec715a46d98e41bc46acb5cd962ced6ca55530cfd1ddadec9f59621593bda80625635d2511948f3ce218a21a

test:
  secret_key_base: 9f19476699e2c46c9f1c07a37f419bdd17b10763724e4b5ccdbfb5a6a10f1ca114ae10043fd245853ffc8095cd77e3c6aad55700b3d17465547fd9c662be8cd4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
